-- Auto-generated by scripts/export-meta-builds.js. Do not hand-edit — regenerate instead.
-- Generated 2026-07-25T20:02:42.084Z.

HotsBBTalentsData = {
  [63] = {
    ["Windrunner Spire"] = {
      sampleSize = 31,
      fetchedAt = 1785009299189,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 31,
          importString = "C8DAMhlVtghLZL4RZzExaQoBYNzwYZmZmFMzIzMzAAAwAAmZmmlllZAA2MzM2GzMzYDAAAAAWMzMz8AAAYMjZMzMzMbAYmhMGjBzwA",
        },
        {
          heroTreeId = 39,
          heroTreeName = "Sunfury",
          sampleSize = 31,
          importString = "C8DAMhlVtghLZL4RZzExaQoBYNzwYZmZmFMzIzMzAAAwAAmZmmlllZAA2MzM2GzMzYDAAAAAWMzMz8AAAYMjZMzMzMbAYmhMGjBzwA",
        },
      },
    },
  },
  [65] = {
    ["Rotmire"] = {
      sampleSize = 49,
      fetchedAt = 1785007769220,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAYBAMDAwglxMMzYmZWYMGPwyYbmZxMNxYGzMDDzWGAGA2AbsNzMzysNzMbNAAAALsxAbeAYGDAAwMDzYMaA",
        },
        {
          heroTreeId = 49,
          heroTreeName = "Lightsmith",
          sampleSize = 25,
          importString = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAYBAMDAAsMzMGzYmZ2YMGzyYbmZxMNxYGzMDDzWGAGA2AbsNjZWmtZmZrBAAAYBA2MjxMMAAgZGmxY0A",
        },
        {
          heroTreeId = 50,
          heroTreeName = "Herald of the Sun",
          sampleSize = 24,
          importString = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAYBAMDAAsMmZmZGzMzihxwyYbmZxMNxwYmZYY2yAwAwGYjtZMAIAgZmltFbzMsxGDsZgZMDAYmBgZMGNA",
        },
      },
    },
  },
  [71] = {
    ["Rotmire"] = {
      sampleSize = 46,
      fetchedAt = 1785009290884,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 46,
          importString = "CcEAjLzRlq54bI5v+r8Sr9Xw4jZmxsMzMzYGAAAghphxYmZbZmZmZYGzMAAAAAGbmB2iBsYGDLwAzoNaMYBMzwwgZzsNYmBAYmhB",
        },
        {
          heroTreeId = 60,
          heroTreeName = "Slayer",
          sampleSize = 3,
          importString = "CcEAjLzRlq54bI5v+r8Sr9Xw4jZmxsMzMzYGAAAghphZGzMLmZmZGmxMDAAAAgxmZgtYAbmxwCMwMajGDWAzMMMY2MbDmZAAmZYA",
        },
        {
          heroTreeId = 62,
          heroTreeName = "Colossus",
          sampleSize = 43,
          importString = "CcEAjLzRlq54bI5v+r8Sr9Xw4jZmxsMzMzYGAAAghphZGmZbZmZmZYGzMAAAAAGbmB2iBsZGDLwAzoNaMYBMzwwgZzsNYmBAYmhB",
        },
      },
    },
  },
  [102] = {
    ["Rotmire"] = {
      sampleSize = 50,
      fetchedAt = 1785009572192,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMD8AmFzMzMAzYMzyYbGzYjlZWGzMjZBDDwAssN2w0MzyIAAAAbMzMzgNjZMmBwMDAMA",
        },
        {
          heroTreeId = 23,
          heroTreeName = "Keeper of the Grove",
          sampleSize = 48,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMD8AmlZmZmBYGjZWGLmZGbsMzyMjZmZBDDwYbbmBjZbEYCAAAwCzMzMYzwYMAAMzADA",
        },
      },
    },
    ["Imperator Averzian"] = {
      sampleSize = 48,
      fetchedAt = 1785009572429,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDMmlZmZmBYYMzyYZGzYjlZWGzMjZBDAGgltxGmmZWGBAAAYzMzMzgNjhxMAmZAgB",
        },
        {
          heroTreeId = 23,
          heroTreeName = "Keeper of the Grove",
          sampleSize = 31,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMD8AmFzMzMAzYMzyYbGzYjlZWGzMjZBDDwAssN2w0MzyIAAAAbMzMzgNjZMmBwMDAMA",
        },
      },
    },
    ["Vorasius"] = {
      sampleSize = 50,
      fetchedAt = 1785009582367,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMD8AmFzMzMAzYMzyYbGzYjlZWGzMjZBDDwAssN2w0MzyIAAAAbMzMzgNjZMmBwMDAMA",
        },
        {
          heroTreeId = 23,
          heroTreeName = "Keeper of the Grove",
          sampleSize = 31,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWAzmZMmZgxsMzMzMAzYMzyYbGzYjlZWGzMjZBDDwAssN2wYmZZAAAAwGzMzMYzAjZAMzAADA",
        },
        {
          heroTreeId = 24,
          heroTreeName = "Elune's Chosen",
          sampleSize = 2,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDwsMmZmBDDjZWmZzYGLsMzyYMzMLYYAGbLzMbbzsNbz0MzyMBAAAYxMzMzgNjZMmBwMDmZgB",
        },
      },
    },
    ["Fallen-King Salhadaar"] = {
      sampleSize = 49,
      fetchedAt = 1785009582714,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMD8AmlZmZmBYGz2MLjthZmNWmZZMzMshhBYAW2GbYamZZEAAAgNmZmZwmhxYGAzMAwA",
        },
        {
          heroTreeId = 23,
          heroTreeName = "Keeper of the Grove",
          sampleSize = 33,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDwsYmZmBDzY2mZZsNMzsxyMLjZmhNMMADw22YDTzMLjAAAAsZmZmZwmhxYGAzMAwA",
        },
      },
    },
    ["Vaelgor & Ezzorak"] = {
      sampleSize = 49,
      fetchedAt = 1785009587105,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDwsYmZmBDzY2mZZsNMzsxyMLjZmhNMMADw22YDTzMLjAAAAsZmZmZwmhxYGAzMAwA",
        },
        {
          heroTreeId = 23,
          heroTreeName = "Keeper of the Grove",
          sampleSize = 38,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDwsYmZmBDzY2mZZsNMzsxyMLjZmhNMMADw22YDTzMLjAAAAsZmZmZwmhxYGAzMAwA",
        },
      },
    },
    ["Lightblinded Vanguard"] = {
      sampleSize = 49,
      fetchedAt = 1785009587189,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMD8AmFzMzMAzYMzyYbGzYjlZWGzMjZBDDwAssN2w0MzyIAAAAbMzMzgNjZMmBwMDAMA",
        },
        {
          heroTreeId = 24,
          heroTreeName = "Elune's Chosen",
          sampleSize = 30,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMD8AmFzMzMAzYMzyYbGzYjlZWGzMjZBDDwAssN2w0MzyIAAAAbMzMzgNjZMmBwMDAMA",
        },
      },
    },
    ["Crown of the Cosmos"] = {
      sampleSize = 49,
      fetchedAt = 1785009591152,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMaGjZG4BMbzMzMDDmhlZ2mxMmxGLzYmZGzshhBYAW2GbYamZZEAAAgNmZmZwmhxYGAzMAwA",
        },
        {
          heroTreeId = 23,
          heroTreeName = "Keeper of the Grove",
          sampleSize = 28,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMaGjZG4BMbzMzMDDmhlZ2mxMmxGLzYmZGzshhBYAW2GbYamZZEAAAgNmZmZwmhxYGAzMAwA",
        },
      },
    },
    ["Chimaerus, the Undreamt God"] = {
      sampleSize = 50,
      fetchedAt = 1785009591893,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMD8AmFzMzMAzYMzyYbGzYjlZWGzMjZBDDwAssN2w0MzyIAAAAbMzMzgNjZMmBwMDAMA",
        },
        {
          heroTreeId = 23,
          heroTreeName = "Keeper of the Grove",
          sampleSize = 37,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWAzmZMmZgxsMzMzMAzYMzyYbGzYjlZWGzMjZBDDwAssN2wYmZZAAAAwGzMzMYzAjZAMzAADA",
        },
      },
    },
    ["Belo'ren, Child of Al'ar"] = {
      sampleSize = 50,
      fetchedAt = 1785009594139,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDMmFzMzMLAjZZmlZWMzM2YZmlxMjxCGGgx22MDGz2IwEAAAgFmZmZwmhxYAAYmBGA",
        },
        {
          heroTreeId = 24,
          heroTreeName = "Elune's Chosen",
          sampleSize = 26,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDMmFzMzMLAjZZmlZWMzM2YZmlxMjxCGGgx22MDGz2IwEAAAgFmZmZwmhxYAAYmBGA",
        },
      },
    },
    ["Midnight Falls"] = {
      sampleSize = 50,
      fetchedAt = 1785009594356,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDMmFzMzMYYYMzyMLmZGbsMzyYmZGLYYAGbbzMYMbjATAAAAWYmZmBbGDjBAgZGYA",
        },
        {
          heroTreeId = 23,
          heroTreeName = "Keeper of the Grove",
          sampleSize = 32,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMD8AmlZmZmBYGjZWGLmZGbsMzyMjZmZBDDwYbbmBjZbEYCAAAwCzMzMYzwYMAAMzADA",
        },
        {
          heroTreeId = 24,
          heroTreeName = "Elune's Chosen",
          sampleSize = 2,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDwsMmZmBDDjZWmZzYGLsMzyYMzMLYYAGbLzMbbzsNbz0MzyMBAAAYxMzMzgNjZMmBwMDmZgB",
        },
      },
    },
    ["Windrunner Spire"] = {
      sampleSize = 26,
      fetchedAt = 1785009600093,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 26,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDMmFzMzMAzY2mZZsNMzsNWmxYmZYDDDwAssN2w0MzyIAAAAbMzMzgNDjxMAmZAgB",
        },
        {
          heroTreeId = 24,
          heroTreeName = "Elune's Chosen",
          sampleSize = 24,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDwsYmZmZhBMLzsMziZmxGLzsMmZMWwwAM22mZwYWGBmAAAAsYmZmZwmxMGDAAzMwA",
        },
      },
    },
    ["Maisara Caverns"] = {
      sampleSize = 30,
      fetchedAt = 1785009600209,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 30,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDwsYmZmZhBMLzsMziZmxGLzsMmZMWwwAM22mZwYWGBmAAAAsYmZmZwmxMGDAAzMwA",
        },
        {
          heroTreeId = 24,
          heroTreeName = "Elune's Chosen",
          sampleSize = 29,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDwsYmZmZhBMLzsMziZmxGLzsMmZMWwwAM22mZwYWGBmAAAAsYmZmZwmxMGDAAzMwA",
        },
      },
    },
    ["Nexus-Point Xenas"] = {
      sampleSize = 20,
      fetchedAt = 1785009609287,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 20,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDwsYmZmZhBjZZmlZWMzM2YZmlxMjxCGGgx22MDGz2IwEAAAgFzMzMD2MMGDAAzMwA",
        },
        {
          heroTreeId = 24,
          heroTreeName = "Elune's Chosen",
          sampleSize = 18,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDwsYmZmZhBjZZmlZWMzM2YZmlxMjxCGGgx22MDGz2IwEAAAgFzMzMD2MMGDAAzMwA",
        },
      },
    },
    ["Algeth'ar Academy"] = {
      sampleSize = 29,
      fetchedAt = 1785009609475,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 29,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMaGjZGYMLjZmZAGsMz2MmxM2YZGzMzYmNMMADwy2YDTzMLjAAAAsZmZmZwmxMGzAYmBAGA",
        },
        {
          heroTreeId = 24,
          heroTreeName = "Elune's Chosen",
          sampleSize = 25,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMaGjZGYMLjZmZAGsMz2MmxM2YZGzMzYmNMMADwy2YDTzMLjAAAAsZmZmZwmxMGzAYmBAGA",
        },
      },
    },
    ["Magisters' Terrace"] = {
      sampleSize = 31,
      fetchedAt = 1785009611406,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 31,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDwsMzMzMLMYMLzsMziZmxGLzsMmZMWwwAM22mZwY2GBmAAAAswMzMD2MMGDAAzMwA",
        },
        {
          heroTreeId = 24,
          heroTreeName = "Elune's Chosen",
          sampleSize = 26,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDwsMzMzMLMYMLzsMziZmxGLzsMmZMWwwAM22mZwY2GBmAAAAswMzMD2MMGDAAzMwA",
        },
      },
    },
    ["Pit of Saron"] = {
      sampleSize = 29,
      fetchedAt = 1785009615594,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 29,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDwsMzMzMLMYMLzsMziZmxGLzsMmZMWwwAM22mZwY2GBmAAAAswMzMD2MMGDAAzMwA",
        },
        {
          heroTreeId = 24,
          heroTreeName = "Elune's Chosen",
          sampleSize = 26,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDwsMzMzMLMYMLzsMziZmxGLzsMmZMWwwAM22mZwY2GBmAAAAswMzMD2MMGDAAzMwA",
        },
      },
    },
    ["Seat of the Triumvirate"] = {
      sampleSize = 27,
      fetchedAt = 1785009616567,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 27,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMaGjZGYMLjZmZAGsMz2MmxM2YZGzMzYmNMMADwy2YDTzMLjAAAAsZmZmZwmxMGzAYmBAGA",
        },
        {
          heroTreeId = 24,
          heroTreeName = "Elune's Chosen",
          sampleSize = 25,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMaGjZGYMLjZmZAGsMz2MmxM2YZGzMzYmNMMADwy2YDTzMLjAAAAsZmZmZwmxMGzAYmBAGA",
        },
      },
    },
    ["Skyreach"] = {
      sampleSize = 28,
      fetchedAt = 1785009618433,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 28,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMbNjxMDwsYmZmZhBMLzsMziZmxGLzsMmZMWwwAM22mZ22mZZ2mpZmlZCAAAwiZmZmBbGzYMAAMzADA",
        },
        {
          heroTreeId = 24,
          heroTreeName = "Elune's Chosen",
          sampleSize = 26,
          importString = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMaGjZGYMLjZmZAGsMz2MmxM2YZGzMzYmNMMADwy2YDTzMLjAAAAsZmZmZwmxMGzAYmBAGA",
        },
      },
    },
  },
  [103] = {
    ["Rotmire"] = {
      sampleSize = 43,
      fetchedAt = 1785009619864,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 43,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAjZwMzMzMmtl5BWGbzYGzMDAAAALBzmhxMjaGziZmZGjZYAAAAAAMwAAAAIAY2mZpZbmlNwMDwiZwAAYmBAD",
        },
        {
          heroTreeId = 22,
          heroTreeName = "Wildstalker",
          sampleSize = 41,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAjZwMzMzMmtl5BWGbzYGzMDAAAALBzmhxMjaGziZmZGjZYAAAAAAMwAAAAIAY2mZpZbmlNwMDwiZwAAYmBAD",
        },
      },
    },
    ["Imperator Averzian"] = {
      sampleSize = 47,
      fetchedAt = 1785009622892,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 47,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAjZwMzMzMmtl5BWGbzYGzMDAAAAbBDDjZG1MmlxMzMGzYGAAAAAADMAAAAamlZbmZmZbmlmtZW2AzMALmBDAgZGMzGG",
        },
        {
          heroTreeId = 22,
          heroTreeName = "Wildstalker",
          sampleSize = 30,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAjZwMzMzMmtl5BWGbzYGzMDAAAALBzmhxMjaGzyYmZGjZMAAAAAAMwAAAAIAY2mZpZbmlNwMDwiZwAAYmBAD",
        },
      },
    },
    ["Vorasius"] = {
      sampleSize = 48,
      fetchedAt = 1785009627437,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAjZwMzMzMmtl5B2GbzYGzMDAAAALBzmhxMjaGzyYmZGjZMAAAAAAMwAAAAIAY2mZpZbmlNwMDwiZwAAYmBAD",
        },
        {
          heroTreeId = 22,
          heroTreeName = "Wildstalker",
          sampleSize = 31,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAjZwMzMzMmtl5B2GbzYGzMDAAAALBzmhxMjaGzyYmZGjZMAAAAAAMwAAAAIAY2mZpZbmlNwMDwiZwAAYmBAD",
        },
      },
    },
    ["Fallen-King Salhadaar"] = {
      sampleSize = 47,
      fetchedAt = 1785009628391,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 47,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAgZMzmZmZmxY2M2GbzMzMmZAAAAYJY2M8AmZUzYWMzMzsMmhBAAAAAwADAAAgmZZWmZmBEDLwMzAswgBAAwMbYA",
        },
        {
          heroTreeId = 22,
          heroTreeName = "Wildstalker",
          sampleSize = 30,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAgZMzmZmZmxY2M2GbzMzMmZAAAAYJY2M8AmZUzYWMzMzsMmhBAAAAAwADAAAgmZZWmZmBEDLwMzAswgBAAwMbYA",
        },
      },
    },
    ["Vaelgor & Ezzorak"] = {
      sampleSize = 47,
      fetchedAt = 1785009631037,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 47,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAgZMzmZmZmxY2M2GbzMzMmZAAAAYJY2M8AmZUzYWMzMzsMmhBAAAAAwADAAAgmZZWmZmBEYBmZGgFGMAAAmZDD",
        },
        {
          heroTreeId = 22,
          heroTreeName = "Wildstalker",
          sampleSize = 31,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAjZwMzMzMmtl5BWGbzYGzMDAAAAbBzmhxMjaGzyYmZGjZYAAAAAAMwAAAAIjZbMzMbzs0sNzyGMz8AALmBDAgZGMzGG",
        },
      },
    },
    ["Lightblinded Vanguard"] = {
      sampleSize = 48,
      fetchedAt = 1785009631752,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAgZMziZmZmxY2M2GbzMzMmZAAAAYJY2M8AmZUzYWMzMzsMmhBAAAAAwADAAAgmZZWmZmBEYBmZGgFGMAAAmZDD",
        },
        {
          heroTreeId = 22,
          heroTreeName = "Wildstalker",
          sampleSize = 34,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAgZMziZmZmxY2M2GbzMzMmZAAAAYJY2M8AmZUzYWMzMzsMmhBAAAAAwADAAAgmZZWmZmBEYBmZGgFGMAAAmZDD",
        },
      },
    },
    ["Crown of the Cosmos"] = {
      sampleSize = 48,
      fetchedAt = 1785009633883,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAjZwMzMzMmtl5BWGbzYGzMDAAAALBzmhxMjaGzyYmZGjZMAAAAAAMwAAAAIAY2mZpZbmlNwMDwiZwAAYmBAD",
        },
        {
          heroTreeId = 22,
          heroTreeName = "Wildstalker",
          sampleSize = 29,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAjZwMzMzMmtl5BWGbzYGzMDAAAALBzmhxMjaGzyYmZGjZMAAAAAAMwAAAAIAY2mZpZbmlNwMDwiZwAAYmBAD",
        },
      },
    },
    ["Chimaerus, the Undreamt God"] = {
      sampleSize = 48,
      fetchedAt = 1785009634563,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAjZwMzMzMmtl5BWGbzYGzMDAAAAbBDDjZG1MmlxMzMGzYGAAAAAADMAAAAamlZbmZmZbmlmtZW2AzMALmBDAgZGMzGG",
        },
        {
          heroTreeId = 22,
          heroTreeName = "Wildstalker",
          sampleSize = 36,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAjZwMzMzMmtl5BWGbzYGzMDAAAALghhxMDmxsMzMzMGzwAAAAAAYgBAAAAAY2mZxsNzyGYmBYxMYAAMzAgB",
        },
      },
    },
    ["Belo'ren, Child of Al'ar"] = {
      sampleSize = 50,
      fetchedAt = 1785009636096,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAgZMziZmZmxY2M2GbzMzMmZAAAAYJY2M8AmZUzYWMzMzsMmhBAAAAAwADAAAgmZZWmZmBEYBmZGgFGMAAAmZDD",
        },
        {
          heroTreeId = 22,
          heroTreeName = "Wildstalker",
          sampleSize = 38,
          importString = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAjZwMzMzMmtl5BWGbzYm5BmZAAAAYBMbGGzMYGzyYmZGjZMAAAAAAMwAAAAAAMbzsY2mZZDMzAsYGMAAmZAwA",
        },
      },
    },
  },
  [250] = {
    ["Rotmire"] = {
      sampleSize = 48,
      fetchedAt = 1785009158080,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMzMMbzMz0MbmZMmxAAAAAzMzMzMzMDzYMAYMzMzAAAMzsNGGzYZrxy2ywklhhNAzwAAwMzMDMMA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 46,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMzMMbzMz0MbmZMmxAAAAAzMzMzMzMDzYMAYMzMzAAAMzsNGGzYZrxy2ywklhhNAzwAAwMzMDMMA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 2,
          importString = nil,
        },
      },
    },
    ["Imperator Averzian"] = {
      sampleSize = 47,
      fetchedAt = 1785009157974,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 47,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMzMMbzMz0MbmZMmxAAAAAzMzMzMzMDzYMAYMzMzAAAMzsNGGzYZrxy2ywklhhNAzwAAwMzMDMMA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 44,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMzMMbzMz0MbmZMmxAAAAAzMzMzMzMDzYMAYMzMzAAAMzsNGGzYZrxy2ywklhhNAzwAAwMzMDMMA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 3,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWmZmxMmZmhZbmZmmZzYMzMGAAAAYmxMzMzMDzYMAYMzMzAAAMmtBGwSw2wEYYBwMmBAgZGAYA",
        },
      },
    },
    ["Vorasius"] = {
      sampleSize = 49,
      fetchedAt = 1785009158046,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMjhZbmZmmZxMjxMmBAAAAzMzMzMzMDzYMAYMzMzAAAYgBmxiGLbgsNgNAzwAAAmZghB",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 46,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMjhZbmZmmZxMjxMmBAAAAzMzMzMzMDzYMAYMzMzAAAYgBmxiGLbgsNgNAzwAAAmZghB",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 3,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMjhZbmZmmZzMjxMmBAAAAmZmZmZmZYGjBAjZmZmBAAMzsNGGzYbpxy22wkthhFAzwAAwMzMDMMA",
        },
      },
    },
    ["Fallen-King Salhadaar"] = {
      sampleSize = 47,
      fetchedAt = 1785009158054,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 47,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWmZGmxMjhZZmZmmZxMjZmxAAAAAmxMzMzMDzMDAYMzMzAAAMzsNGGzYZpxy22wklhhNAzYmBAwMzMDMMA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 41,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMjhZbmZmmZxMjxMmBAAAAzMzMzMzMDzYMAYMzMzAAAYgBmxiGLbgsNgNAzwAAAmZghB",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 6,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMjhZbmZmmZxMjxMGAAAAYmZmZGzMDzYMAgZmZGAAgZmtxwYGLLN2WWGmsNMsAYGzMAAmZAmhB",
        },
      },
    },
    ["Vaelgor & Ezzorak"] = {
      sampleSize = 47,
      fetchedAt = 1785009173923,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 47,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMjhZbmZmmZxMjxMGAAAAYmZmZmZmZYGjBAjZmZGAAADMwM20YZDktBsBYGGAAwMDmhB",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 46,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMjhZbmZmmZxMjxMGAAAAYmZmZmZmZYGjBAjZmZGAAADMwM20YZDktBsBYGGAAwMDmhB",
        },
      },
    },
    ["Lightblinded Vanguard"] = {
      sampleSize = 48,
      fetchedAt = 1785009174093,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMzMMbzMz0MbmZMmxAAAAAzMzMzMzMDzYMAYMzMzAAAMzsNGGzYZrxy2ywklhhNAzwAAwMzMDMMA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 48,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMzMMbzMz0MbmZMmxAAAAAzMzMzMzMDzYMAYMzMzAAAMzsNGGzYZrxy2ywklhhNAzwAAwMzMDMMA",
        },
      },
    },
    ["Crown of the Cosmos"] = {
      sampleSize = 48,
      fetchedAt = 1785009174649,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMjhZbmZmmZzMjxMGAAAAYmZmZmZmZYGjBAjZmZGAAgZmtxwYGLLNW22GmsNMsAYGGAAmZmZwMMA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 41,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMjhZbmZmmZzMjxMGAAAAYmZmZmZmZYGjBAjZmZGAAgZmtxwYGLLNW22GmsNMsAYGGAAmZmZwMMA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 7,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzMmxMzMMbzMz0MLmZMzMAAAAAGMzMzMjZmZMAYmZmZGAAgZmtxwYGLLNW2WGmsNMsAYGDAAmZAgB",
        },
      },
    },
    ["Chimaerus, the Undreamt God"] = {
      sampleSize = 49,
      fetchedAt = 1785009174960,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMzMMbzMz0MbmZMmxAAAAAzMzMzMzMDzYMAYMzMzAAAMzsNGGzYZrxy2ywklhhNAzwAAwMzMDMMA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 44,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMzMMbzMz0MbmZMmxAAAAAzMzMzMzMDzYMAYMzMzAAAMzsNGGzYZrxy2ywklhhNAzwAAwMzMDMMA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 5,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMzMMbzMz0MLGjxMGAAAAwMzMzMzMDzMjBAMzMzAAAMzsNGGzYZpxyy2wkthhFAzYGAAmZmZwMMA",
        },
      },
    },
    ["Belo'ren, Child of Al'ar"] = {
      sampleSize = 50,
      fetchedAt = 1785009180072,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMjhZbmZmmZxMjxMmBAAAAzMzMzMzMDzYMAYMzMzAAAYgBmxiGLbgsNgNAzwAAAmZghB",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 44,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMjhZbmZmmZxMjxMmBAAAAzMzMzMzMDzYMAYMzMzAAAYgBmxiGLbgsNgNAzwAAAmZghB",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 6,
          importString = nil,
        },
      },
    },
    ["Midnight Falls"] = {
      sampleSize = 48,
      fetchedAt = 1785009180239,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMjhZbmZmmZxMjxMmBAAAAzMzMzMzMDzYMAYMzMzAAAYgBmxiGLbgsNgNAzwAAAmZghB",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 43,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMjhZbmZmmZxMjxMmBAAAAzMzMzMzMDzYMAYMzMzAAAYgBmxiGLbgsNgNAzwAAAmZghB",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 5,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMzMMbzMz0MLmZmxMAAAAAmZmZmZmZYGjBAjZmZGAAgZmtxwYGLLNW22GmsNMsAYGzAAwMzMDGMA",
        },
      },
    },
    ["Windrunner Spire"] = {
      sampleSize = 38,
      fetchedAt = 1785009180408,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 38,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzwMmxgZbmZmmZZmZMzMGAAAAwgZmZmZMzMjBAzMzMzAAAMzsNGGzYZpx22ywkthhFAzYAAwMzMDYMA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 38,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzwMmxgZbmZmmZZmZMzMGAAAAwgZmZmZMzMjBAzMzMzAAAMzsNGGzYZpx22ywkthhFAzYAAwMzMDYMA",
        },
      },
    },
    ["Maisara Caverns"] = {
      sampleSize = 36,
      fetchedAt = 1785009181149,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 36,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzMmxMzMMbzMz0MLmZMzMAAAAAGMzMzMjZmZMAYmZmZGAAgZmtxwYGLLNW22GmsNMsAYGDAAmZmZAMA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 2,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMzMMLzMz0MLGjxMmBAAAAzMzMzMzMDzYMAYMzMzAAAYgBmxiGLbgsNgNAzwAAAmZghB",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 34,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzMmxMzMMbzMz0MLmZMzMAAAAAGMzMzMjZmZMAYmZmZGAAgZmtxwYGLLNW22GmsNMsAYGDAAmZmZAMA",
        },
      },
    },
    ["Nexus-Point Xenas"] = {
      sampleSize = 45,
      fetchedAt = 1785009213056,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 45,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzMmxMzMMbzMz0MLmZMzMAAAAAGMzMzMjZmZMAYmZmZGAAgZmtxwYGLLNW22GmsNMsAYGDAAmZmZAMA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 3,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMzMMLzMz0MLGjxMmBAAAAzMzMzMzMDzYMAYMzMzAAAYgBmxiGLbgsNgNAzwAAAmZghB",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 42,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzMmxMzMMbzMz0MLmZMzMAAAAAGMzMzMjZmZMAYmZmZGAAgZmtxwYGLLNW22GmsNMsAYGDAAmZmZAMA",
        },
      },
    },
    ["Algeth'ar Academy"] = {
      sampleSize = 43,
      fetchedAt = 1785009213299,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 43,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzwMmZmhZZmZmmZZmZMmBAAAAwgZmZmZMzMjBAzMzMzAAAMmtBGwSwywEYYBwMGAAMzAMYA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 4,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMzMMLzMz0MLGjxMmBAAAAzMzMzMzMDzYMAYMzMzAAAYgBmxiGLbgsNgNAzwAAAmZghB",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 39,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzwMmZmhZZmZmmZZmZMmBAAAAwgZmZmZMzMjBAzMzMzAAAMmtBGwSwywEYYBwMGAAMzAMYA",
        },
      },
    },
    ["Magisters' Terrace"] = {
      sampleSize = 39,
      fetchedAt = 1785009213446,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 39,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzwMmxgZbmZmmZZmZMzMAAAAAGMzMzMjZmZMAYmZmZGAAgxsNwAWCWGmADLAmxAAgZGgxYA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 2,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMzMMLzMz0MLGjxMmBAAAAzMzMzMzMDzYMAYMzMzAAAYgBmxiGLbgsNgNAzwAAAmZghB",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 37,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzwMmxgZbmZmmZZmZMzMAAAAAGMzMzMjZmZMAYmZmZGAAgxsNwAWCWGmADLAmxAAgZGgxYA",
        },
      },
    },
    ["Pit of Saron"] = {
      sampleSize = 39,
      fetchedAt = 1785009213179,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 39,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzwMmZmhZZmZmmZZmZMmBAAAAwgZmZmZMzMjBAzMzMzAAAMmtBGwSwywEYYBwMGAAMzAMYA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 3,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxYWGzMmxMzMMLzMz0MLGjxMmBAAAAzMzMzMzMDzYMAYMzMzAAAYgBmxiGLbgsNgNAzwAAAmZghB",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 36,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzwMmZmhZZmZmmZZmZMmBAAAAwgZmZmZMzMjBAzMzMzAAAMmtBGwSwywEYYBwMGAAMzAMYA",
        },
      },
    },
    ["Seat of the Triumvirate"] = {
      sampleSize = 35,
      fetchedAt = 1785009214073,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 35,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzwMmxgZbmZmmZZmZMzMGAAAAwgZmZmZMzMjBAzMzMzAAAMzsNGGzYZpx22ywkthhFAzYAAwMzMDYMA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 2,
          importString = nil,
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 33,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzwMmxgZbmZmmZZmZMzMGAAAAwgZmZmZMzMjBAzMzMzAAAMzsNGGzYZpx22ywkthhFAzYAAwMzMDYMA",
        },
      },
    },
    ["Skyreach"] = {
      sampleSize = 38,
      fetchedAt = 1785009214149,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 38,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzwMmZmhZZmZmmZZmZMmBAAAAwgZmZmZMzMjBAzMzMzAAAMmtBGwSwywEYYBwMGAAMzAMYA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 38,
          importString = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzwMmZmhZZmZmmZZmZMmBAAAAwgZmZmZMzMjBAzMzMzAAAMmtBGwSwywEYYBwMGAAMzAMYA",
        },
      },
    },
  },
  [251] = {
    ["Rotmire"] = {
      sampleSize = 50,
      fetchedAt = 1785009214146,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDwMjZMGDz2MzMzMbmZ0MjxYYGGMzMzMzMzMDAAAAAAAAAjZbgBsAWGmQGLYmxMzADADzMAzAD",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 49,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDwMjZMGDz2MzMzMbmZ0MjxYYGGMzMzMzMzMDAAAAAAAAAjZbgBsAWGmQGLYmxMzADADzMAzAD",
        },
      },
    },
    ["Imperator Averzian"] = {
      sampleSize = 48,
      fetchedAt = 1785009214268,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDwMjZMzYY2mZmZmZxMDmxYMMDDmZmZmZmZmBAAAAAAAAgxsNwAWALDDwYBzMmZGYAYYmBYGYA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 47,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDYmhZMGDz2MzMzMLmZ0MjxYYGGMzMzMzMzMDAAAAAAAAAjZbgBsAWGmQGLYmxMzADADzMAzAD",
        },
      },
    },
    ["Vorasius"] = {
      sampleSize = 50,
      fetchedAt = 1785009228714,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDYmZMjZMY2mZmZmZzMDmxYMMDDmZmZmZmZmBAAAAAAAAgxsNwAWALDDwYBzMmZGYAYYmBYGYA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 45,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDwMjZMGDz2MzMzMLzMjMjxYYGGMzMzMzMzMDAAAAAAAAAjZbgBsAWGmQGLYmxMzADADzMAmBD",
        },
      },
    },
    ["Fallen-King Salhadaar"] = {
      sampleSize = 48,
      fetchedAt = 1785009228885,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDwMjZMGDz2MzMzMbzMjMjxMDzw4BMzgZmZmZAAAAAAAAAYMbDMgFwywEyYBzMmZGYGADzMAjBD",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 45,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDwMjZMGDz2MzMzMbzMjMjxMDzw4BMzgZmZmZAAAAAAAAAYMbDMgFwywEyYBzMmZGYGADzMAjBD",
        },
      },
    },
    ["Vaelgor & Ezzorak"] = {
      sampleSize = 48,
      fetchedAt = 1785009229004,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDwMjZMGDz2MzMzMLzMjMjxYYGGMzMzMzMzMDAAAAAAAAAjZbgBsAWGmQGLYmxMzADADzMAjBD",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 45,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDwMjZMGDz2MzMzMLzMjMjxYYGGMzMzMzMzMDAAAAAAAAAjZbgBsAWGmQGLYmxMzADADzMAjBD",
        },
      },
    },
    ["Lightblinded Vanguard"] = {
      sampleSize = 50,
      fetchedAt = 1785009229229,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDYmhZMzYY2MzMzMbzMjmZMGDzwgZmZmZmZmZAAAAAAAAAYMbzmZbGGLMsMz20QzYBzMmZGYAYYmBzMMYA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 50,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDYmhZMzYY2MzMzMbzMjmZMGDzwgZmZmZmZmZAAAAAAAAAYMbzmZbGGLMsMz20QzYBzMmZGYAYYmBzMMYA",
        },
      },
    },
    ["Crown of the Cosmos"] = {
      sampleSize = 50,
      fetchedAt = 1785009230689,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDwMjZMGDz2MzMzMbmZ0MjxMDzw4BMzgZmZmZAAAAAAAAAYMbzmZbGGLMsMz20QzYBzMmZGYGADzMAzAD",
        },
        {
          heroTreeId = 32,
          heroTreeName = "Rider of the Apocalypse",
          sampleSize = 2,
          importString = nil,
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 47,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDwMjZMGDz2MzMzMbmZ0MjxMDzw4BMzgZmZmZAAAAAAAAAYMbzmZbGGLMsMz20QzYBzMmZGYGADzMAzAD",
        },
      },
    },
    ["Chimaerus, the Undreamt God"] = {
      sampleSize = 48,
      fetchedAt = 1785009230751,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDwMjZMGDz2MzMzMLzMDmxYMMDDmZmZmZmZmBAAAAAAAAgxsNwAWALDDwYBzMmZGYAYYmBYGYA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 46,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDwMjZMGDz2MzMzMLzMDmxYMMDDmZmZmZmZmBAAAAAAAAgxsNwAWALDDwYBzMmZGYAYYmBYGYA",
        },
      },
    },
    ["Belo'ren, Child of Al'ar"] = {
      sampleSize = 50,
      fetchedAt = 1785009230946,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDwMjZMGDz2MzMzMLmZmMjxYYGGMzMzMzMzMDAAAAAAAAAjZb2MLzwYhhlZ2mGaGLYmxMzADADzMAzAD",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 47,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDwMjZMGDz2MzMzMLzMDmxYMMDDmZmZmZmZmBAAAAAAAAgxsNwAWALDDwYBzMmZGYAYYmBYMYA",
        },
      },
    },
    ["Midnight Falls"] = {
      sampleSize = 50,
      fetchedAt = 1785009231498,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDYmhZMzYY2MzMzMbzMjmZMGDzwgZmZmZmZmZAAAAAAAAAYMbzmZbGGLMsMz20QzYBzMmZGYAYYmBzMMYA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 50,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNDYmhZMzYY2MzMzMbzMjmZMGDzwgZmZmZmZmZAAAAAAAAAYMbzmZbGGLMsMz20QzYBzMmZGYAYYmBzMMYA",
        },
      },
    },
    ["Windrunner Spire"] = {
      sampleSize = 32,
      fetchedAt = 1785009233194,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 32,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNAzMMjZGzYWmZmZmZzMjmZMmZmZGYMzwMzMjZAAAAAAAAAYMbDMgFwywEyYBzMMzAzAYYmBAYA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 32,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNAzMMjZGzYWmZmZmZzMjmZMmZmZGYMzwMzMjZAAAAAAAAAYMbDMgFwywEyYBzMMzAzAYYmBAYA",
        },
      },
    },
    ["Maisara Caverns"] = {
      sampleSize = 33,
      fetchedAt = 1785009359928,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 33,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNAzMMjxYGzyMzMzMbzMjMjxMzMzAjZGmZmZMDAAAAAAAAAjZb2MLzwYhhlZ2mGaGLYmhZGYGADzMAMYA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 33,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNAzMMjxYGzyMzMzMbzMjMjxMzMzAjZGmZmZMDAAAAAAAAAjZb2MLzwYhhlZ2mGaGLYmhZGYGADzMAMYA",
        },
      },
    },
    ["Nexus-Point Xenas"] = {
      sampleSize = 37,
      fetchedAt = 1785009360157,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 37,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNAzMjZMGDzyMzMzMbzY0MjxMzMzAjZGmZmZMDAAAAAAAAAjZbgBsAWGmQGLYmhZGYGADzMAMYA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 37,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNAzMjZMGDzyMzMzMbzY0MjxMzMzAjZGmZmZMDAAAAAAAAAjZbgBsAWGmQGLYmhZGYGADzMAMYA",
        },
      },
    },
    ["Algeth'ar Academy"] = {
      sampleSize = 38,
      fetchedAt = 1785009363381,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 38,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNAzMMjZGzYWmZmZmZzMjmZMmZmZGYMzwMzMjZAAAAAAAAAYMbDMgFwywEyYBzMMzAzAYYmBAYA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 38,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNAzMMjZGzYWmZmZmZzMjmZMmZmZGYMzwMzMjZAAAAAAAAAYMbDMgFwywEyYBzMMzAzAYYmBAYA",
        },
      },
    },
    ["Magisters' Terrace"] = {
      sampleSize = 37,
      fetchedAt = 1785009365361,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 37,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNAzMMjxYY2mZmZmZbmZ0MjxMzMzAjZGmZmZMDAAAAAAAAAjZb2MLzwYhhlZ2mGaGLYmhZGYGADzMAMYA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 37,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNAzMMjxYY2mZmZmZbmZ0MjxMzMzAjZGmZmZMDAAAAAAAAAjZb2MLzwYhhlZ2mGaGLYmhZGYGADzMAMYA",
        },
      },
    },
    ["Pit of Saron"] = {
      sampleSize = 43,
      fetchedAt = 1785009368275,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 43,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNAzMMjxYY2mZmZmZbmZ0MjxMzMzAjZGmZmZMDAAAAAAAAAjZb2MLzwYhhlZ2mGaGLYmhZGYGADzMAMYA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 43,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNAzMMjxYY2mZmZmZbmZ0MjxMzMzAjZGmZmZMDAAAAAAAAAjZb2MLzwYhhlZ2mGaGLYmhZGYGADzMAMYA",
        },
      },
    },
    ["Seat of the Triumvirate"] = {
      sampleSize = 37,
      fetchedAt = 1785009368748,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 37,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNAzMMjZGzYWmZmZmZzMjmZMmZmZGYMzwMzMjZAAAAAAAAAYMbDMgFwywEyYBzMMzAzAYYmBAYA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 37,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNAzMMjZGzYWmZmZmZzMjmZMmZmZGYMzwMzMjZAAAAAAAAAYMbDMgFwywEyYBzMMzAzAYYmBAYA",
        },
      },
    },
    ["Skyreach"] = {
      sampleSize = 42,
      fetchedAt = 1785009372914,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 42,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNAzMMjxYY2mZmZmZbmZ0MjxMzMzAjZGmZmZMDAAAAAAAAAjZb2MLzwYhhlZ2mGaGLYmhZGYGADzMAMYA",
        },
        {
          heroTreeId = 33,
          heroTreeName = "Deathbringer",
          sampleSize = 42,
          importString = "CsPAkXBWxkyfx9CbGaHonEAhLNAzMMjxYY2mZmZmZbmZ0MjxMzMzAjZGmZmZMDAAAAAAAAAjZb2MLzwYhhlZ2mGaGLYmhZGYGADzMAMYA",
        },
      },
    },
  },
  [252] = {
    ["Rotmire"] = {
      sampleSize = 49,
      fetchedAt = 1785009374316,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmhZMmZY2mZmZa2MzYmZMAAAAAAAAMzYYAwyMmZ2MzYmZAbmNDDZgZjhGLYAzAwYmZMDwMzwYA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 12,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmZMjZMYWGzMTjZmxMzYAAAAAAAAYmxwAglZMzsZmxMzA2MbGGyAzGDNWwAmBgxMzYGgZmxMG",
        },
        {
          heroTreeId = 32,
          heroTreeName = "Rider of the Apocalypse",
          sampleSize = 37,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmhZMmZY2mZmZa2MzYmZMAAAAAAAAMzYYAwyMmZ2MzYmZAbmNDDZgZjhGLYAzAwYmZMDwMzwYA",
        },
      },
    },
    ["Imperator Averzian"] = {
      sampleSize = 50,
      fetchedAt = 1785009378096,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMDDz2MzMTzmZmZMjBAAAAAAAgZGmZAw2MmZ2mZGjZAbmFDDZgZjhGLAYGAGzMjZAmZmxYA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 5,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMDY2mZmZa2mZGjZMAAAAAAAAMzwMDA2mxMz2MzYMDYzsYYIDMbM0YBAzAwYmZMDwMzMzYA",
        },
        {
          heroTreeId = 32,
          heroTreeName = "Rider of the Apocalypse",
          sampleSize = 44,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMDDz2MzMTzmZmZMjBAAAAAAAgZGmZAw2MmZ2mZGjZAbmFDDZgZjhGLAYGAGzMjZAmZmxYA",
        },
      },
    },
    ["Vorasius"] = {
      sampleSize = 49,
      fetchedAt = 1785009384780,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMzYY2mZmZMLmZMmxAAAAAAAAwMDzMAYZGzMbzMjxMgFzihBGY2YwYBAzAwYmZMDwMzMGD",
        },
        {
          heroTreeId = 32,
          heroTreeName = "Rider of the Apocalypse",
          sampleSize = 44,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMzYY2mZmZMLmZMmxAAAAAAAAwMDzMAYZGzMbzMjxMgFzihBGY2YwYBAzAwYmZMDwMzMGD",
        },
      },
    },
    ["Fallen-King Salhadaar"] = {
      sampleSize = 46,
      fetchedAt = 1785009384931,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 46,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMDDz2MzMTzmZmZMjBAAAAAAAgZGmZAw2MmZ2mZGjZAbmFDDZgZjhGLAYGAGzMjZAmZmxYA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 7,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMzYY2mZmZaYmxMzYGAAAAAAAAzMMGAsMjZmNzMmZGwmZzwQGY2YoxCGwMAMmZGzAMzMMG",
        },
        {
          heroTreeId = 32,
          heroTreeName = "Rider of the Apocalypse",
          sampleSize = 38,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmZMjZmZYWGzMTDzMmZGDAAAAAAAAzMGGAsMjZmNzMmZGD2mZzMzsoZWWY2Y2mGLYAzAwYmZMDwMzwYA",
        },
      },
    },
    ["Vaelgor & Ezzorak"] = {
      sampleSize = 49,
      fetchedAt = 1785009388338,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMDjxYY2mZmZaMzMmZGzAAAAAAAAYmhZGAsNjZmtZmxYGwiZxwQGY2YoxCAmBgxMzYGgZmZMG",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 35,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMDjxYY2mZmZaMzMmZGzAAAAAAAAYmhZGAsNjZmtZmxYGwiZxwQGY2YoxCAmBgxMzYGgZmZMG",
        },
        {
          heroTreeId = 32,
          heroTreeName = "Rider of the Apocalypse",
          sampleSize = 12,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMGDz2YmZa2mZGzMjBAAAAAAAgZGmZAw2MmZ2mZGjZALmFDDZgZjhGLAYGAGzMjZAmZGzYA",
        },
      },
    },
    ["Lightblinded Vanguard"] = {
      sampleSize = 50,
      fetchedAt = 1785009388381,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMzYY2mZmZa2MzYMjBAAAAAAAgZGGDAWmxMzmZGzMjBbzsYmZ20MLLMbMbTjFMgZAYMzMmBzMzMzYMA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 7,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmhZMmZY2mZmZa2MzYmZMAAAAAAAAMzYYAwyMmZ2MzYmZAbmFDDZgZjhGLYAzAwYmZMDwMzwYA",
        },
        {
          heroTreeId = 32,
          heroTreeName = "Rider of the Apocalypse",
          sampleSize = 38,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMzYY2mZmZa2MzYMjBAAAAAAAgZGGDAWmxMzmZGzMjBbzsYmZ20MLLMbMbTjFMgZAYMzMmBzMzMzYMA",
        },
      },
    },
    ["Crown of the Cosmos"] = {
      sampleSize = 48,
      fetchedAt = 1785009392858,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMzYY2mZmZaWMzYMjBAAAAAAAgZGmZAw2MmZ2mZGjZAbmFDDZgZjhGLAYGAGzMjZAmZmxYA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 4,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMzYY2mZmZa2MzYMjBAAAAAAAgZGmZAw2MmZ2mZGjZAbmFDDZgZjhGLAYGAGzMjZAmZmxYA",
        },
        {
          heroTreeId = 32,
          heroTreeName = "Rider of the Apocalypse",
          sampleSize = 44,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMzYY2mZmZaWMzYMjBAAAAAAAgZGmZAw2MmZ2mZGjZAbmFDDZgZjhGLAYGAGzMjZAmZmxYA",
        },
      },
    },
    ["Chimaerus, the Undreamt God"] = {
      sampleSize = 48,
      fetchedAt = 1785009394221,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMzYY2mZmZaWMzYMjBAAAAAAAgZGmZAw2MmZ2mZGjZAbmFDDZgZjhGLAYGAGzMjZAmZmxYA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 2,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmhZMGDz2MzMTziZGzMjBAAAAAAAgZGDDAWmxMzmZGzMjBLzsZmZW0MLbMbMbTjFMgZAYMzMmBzMzMzYMA",
        },
        {
          heroTreeId = 32,
          heroTreeName = "Rider of the Apocalypse",
          sampleSize = 43,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmBjxMDz2MzMTzmxYmZMDAAAAAAAgZGDDAWmxMzmZGzMDYxsYYIDMbM0YBDYGAGzMjZAmZmxYA",
        },
      },
    },
    ["Belo'ren, Child of Al'ar"] = {
      sampleSize = 49,
      fetchedAt = 1785009395654,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmhZMjBz2MzMTjZmxMzYAAAAAAAAYmxwAglZMzsZmxMzA2MbGGyAzGDNWwAmBgxMzYGgZmxMG",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 5,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMzYY2mZmZaYmxMzYAAAAAAAAYmhZGAsNjZmtZmxYGwmZxwQGY2YoxCAmBgxMzYGgZmZMG",
        },
        {
          heroTreeId = 32,
          heroTreeName = "Rider of the Apocalypse",
          sampleSize = 39,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmhZMjBz2MzMTjZmxMzYAAAAAAAAYmxwAglZMzsZmxMzA2MbGGyAzGDNWwAmBgxMzYGgZmxMG",
        },
      },
    },
    ["Midnight Falls"] = {
      sampleSize = 48,
      fetchedAt = 1785009396519,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMzYY2mZmZa2MzYMjBAAAAAAAgZGmZAw2MmZ2mZGjZMYbmFzMzimZZhZjZbasAgZAYMzMmBzMzMzYMA",
        },
        {
          heroTreeId = 31,
          heroTreeName = "San'layn",
          sampleSize = 3,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMDDz2MzMTzmZmZMjBAAAAAAAgZGmZAw2MmZ2mZGjZAbmFDDZgZjhGLAYGAGzMjZAmZmxYA",
        },
        {
          heroTreeId = 32,
          heroTreeName = "Rider of the Apocalypse",
          sampleSize = 43,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBwMjZMzYY2mZmZaWMzYYMDAAAAAAAgZGmZAw2MmZ2mZGjZAbmFDDZgZjhGLAYGAGzMjZAmZmxYA",
        },
      },
    },
    ["Windrunner Spire"] = {
      sampleSize = 32,
      fetchedAt = 1785009400317,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 32,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmZMjZMYWGzMTjZmxMzYAAAAAAAAYmxwAglZMzsZmxMzA2MbGGyAzGDNWwAmBgxMzYGgZmxMG",
        },
        {
          heroTreeId = 32,
          heroTreeName = "Rider of the Apocalypse",
          sampleSize = 32,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmZMjZMYWGzMTjZmxMzYAAAAAAAAYmxwAglZMzsZmxMzA2MbGGyAzGDNWwAmBgxMzYGgZmxMG",
        },
      },
    },
    ["Maisara Caverns"] = {
      sampleSize = 9,
      fetchedAt = 1785009400448,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 9,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmZMjZMYWGzMTjZmxMzYAAAAAAAAYmxwAglZMzsZmxMzA2MbGGyAzGDNWwAmBgxMzYGgZmxMG",
        },
        {
          heroTreeId = 32,
          heroTreeName = "Rider of the Apocalypse",
          sampleSize = 9,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmZMjZMYWGzMTjZmxMzYAAAAAAAAYmxwAglZMzsZmxMzA2MbGGyAzGDNWwAmBgxMzYGgZmxMG",
        },
      },
    },
    ["Magisters' Terrace"] = {
      sampleSize = 34,
      fetchedAt = 1785009415979,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 34,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmZMjZMYWGzMTjZmxMzYAAAAAAAAYmxwAglZMzsZmxMzA2MbGGyAzGDNWwAmBgxMzYGgZmxMG",
        },
        {
          heroTreeId = 32,
          heroTreeName = "Rider of the Apocalypse",
          sampleSize = 34,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmZMjZMYWGzMTjZmxMzYAAAAAAAAYmxwAglZMzsZmxMzA2MbGGyAzGDNWwAmBgxMzYGgZmxMG",
        },
      },
    },
    ["Pit of Saron"] = {
      sampleSize = 35,
      fetchedAt = 1785009416038,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 35,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmZMjxMDzyMzMTDzMmZGDAAAAAAAAzMMzAgtZMzsNzMGzA2MbGGyAzGDNWAwMAMmZGzAMzMMG",
        },
        {
          heroTreeId = 32,
          heroTreeName = "Rider of the Apocalypse",
          sampleSize = 35,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmZMjxMDzyMzMTDzMmZGDAAAAAAAAzMMzAgtZMzsNzMGzA2MbGGyAzGDNWAwMAMmZGzAMzMMG",
        },
      },
    },
    ["Seat of the Triumvirate"] = {
      sampleSize = 31,
      fetchedAt = 1785009423022,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 31,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmZMjZMYWGzMTz2MzYmZMAAAAAAAAMzYYAwyMmZ2MzYmZMYbmNzMzimZZhZjZZasgBMDAjZmxMYmZmZYMA",
        },
        {
          heroTreeId = 32,
          heroTreeName = "Rider of the Apocalypse",
          sampleSize = 31,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmZMjZMYWGzMTz2MzYmZMAAAAAAAAMzYYAwyMmZ2MzYmZMYbmNzMzimZZhZjZZasgBMDAjZmxMYmZmZYMA",
        },
      },
    },
    ["Skyreach"] = {
      sampleSize = 37,
      fetchedAt = 1785009428038,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 37,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmZMjZMYWGzMTz2MzYmZMAAAAAAAAMzYYAwyMmZ2MzYmZMYbmNzMzimZZhZjZZasgBMDAjZmxMYmZmZYMA",
        },
        {
          heroTreeId = 32,
          heroTreeName = "Rider of the Apocalypse",
          sampleSize = 37,
          importString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmZMjZMYWGzMTz2MzYmZMAAAAAAAAMzYYAwyMmZ2MzYmZMYbmNzMzimZZhZjZZasgBMDAjZmxMYmZmZYMA",
        },
      },
    },
  },
  [253] = {
    ["Rotmire"] = {
      sampleSize = 49,
      fetchedAt = 1785005613820,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "C0PApei1JmYNvFfEFaN5bWuGKYzsNjZmhFDLMzMbGaGbAAYGPwyMzsYGmZmZGzMMzMmhZGzMzYbmZMjZYZMNDAAAAAAAAwDMGDzMzshAmFwyAA",
        },
        {
          heroTreeId = 43,
          heroTreeName = "Pack Leader",
          sampleSize = 49,
          importString = "C0PApei1JmYNvFfEFaN5bWuGKYzsNjZmhFDLMzMbGaGbAAYGPwyMzsYGmZmZGzMMzMmhZGzMzYbmZMjZYZMNDAAAAAAAAwDMGDzMzshAmFwyAA",
        },
      },
    },
  },
  [577] = {
    ["Rotmire"] = {
      sampleSize = 50,
      fetchedAt = 1785009430303,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZGzMz2MmZmxMzkxMDAAAAAAY2MmtZYmBzM2mt5BmZMGDLDsMLmxwsppxMzYYDAAAAAABAzMYAIAAwA",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 43,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZGzMz2MmZmxMzkxMDAAAAAAY2MmtZYmBzM2mt5BmZMGDLDsMLmxwsppxMzYYDAAAAAABAzMYAIAAwA",
        },
        {
          heroTreeId = 35,
          heroTreeName = "Aldrachi Reaver",
          sampleSize = 2,
          importString = nil,
        },
      },
    },
    ["Imperator Averzian"] = {
      sampleSize = 48,
      fetchedAt = 1785009434315,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZGzMz2MmZmZmZmwMDAAAAAAY2MmtZYmBzM2mt5BmZMGDLDsMLmxwsppxMzYYDAAAAAABAzMYAIAAwA",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 40,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZGzMz2MmZmZmZmwMDAAAAAAY2MmtZYmBzM2mt5BmZMGDLDsMLmxwsppxMzYYDAAAAAABAzMYAIAAwA",
        },
      },
    },
    ["Vorasius"] = {
      sampleSize = 50,
      fetchedAt = 1785009436596,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZMjZmZMzMhZGAAAAAAwsYmZbmBzsNmx2sNmhxwYZgtZzMGmNNNmZmZYDAAAAAABAzMYAIAAwA",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 44,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZMjZmZMzMhZGAAAAAAwsYmZbmBzsNmx2sNmhxwYZgtZzMGmNNNmZmZYDAAAAAABAzMYAIAAwA",
        },
      },
    },
    ["Fallen-King Salhadaar"] = {
      sampleSize = 48,
      fetchedAt = 1785009440255,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZGzMz2MmZmZmZmwMDAAAAAAY2MmtZYmBzM2mt5BmZMGDLDsMLmxwsppxMzYYDAAAAAABAzMYAIAAwA",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 38,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZGzMz2MmZmZmZmwMDAAAAAAY2MmtZYmBzM2mt5BmZMGDLDsMLmxwsppxMzYYDAAAAAABAzMYAIAAwA",
        },
      },
    },
    ["Vaelgor & Ezzorak"] = {
      sampleSize = 49,
      fetchedAt = 1785009440397,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZ2mxMzMGzkxMDAAAAAAYWMmtxDYmBmx2sNzMjxALDsMbmxwsopxMzYGbAAAADAABAzMYAIAAwA",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 43,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZ2mxMzMGzkxMDAAAAAAYWMmtxDYmBmx2sNzMjxALDsMbmxwsopxMzYGbAAAADAABAzMYAIAAwA",
        },
      },
    },
    ["Lightblinded Vanguard"] = {
      sampleSize = 50,
      fetchedAt = 1785009444800,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZ2mxMzMzYmMmZAAAAAAAzmxsNDzMwM2mtZmZMGYZglZzMGmFNNmZGDbAAAADAABAzMYAIAAwA",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 44,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZ2mxMzMzYmMmZAAAAAAAzmxsNDzMwM2mtZmZMGYZglZzMGmFNNmZGDbAAAADAABAzMYAIAAwA",
        },
      },
    },
    ["Crown of the Cosmos"] = {
      sampleSize = 49,
      fetchedAt = 1785009445871,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZGzMz2MmZmxMzkxMDAAAAAAY2MmtZYmBzM2mt5BmZMGDLDsNLmxwsppxMzYYDAAAAAABAzMYAIAAwA",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 37,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZGzMz2MmZmxMzkxMDAAAAAAY2MmtZYmBzM2mt5BmZMGDLDsNLmxwsppxMzYYDAAAAAABAzMYAIAAwA",
        },
      },
    },
    ["Chimaerus, the Undreamt God"] = {
      sampleSize = 50,
      fetchedAt = 1785009446781,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZGzMz2MmZmZmZmwMDAAAAAAY2MmtZYmBzM2mt5BmZMGDLDsNLmxwsppxMzYYDAAAAAABAzMYAIAAwA",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 46,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZGzMz2MmZmZmZmwMDAAAAAAY2MmtZYmBzM2mt5BmZMGDLDsNLmxwsppxMzYYDAAAAAABAzMYAIAAwA",
        },
      },
    },
    ["Belo'ren, Child of Al'ar"] = {
      sampleSize = 49,
      fetchedAt = 1785009450702,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZGzMz2MmZmxMzkxMDAAAAAAY2MmtZYmBzM2mt5BmZMGDLDsMLmxwsppxMzYYDAAAAAABAzMYAIAAwA",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 39,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZGzMz2MmZmZmZmMMDAAAAAAY2MmtZYmBzM2mt5BmZMGDLzsMzysMzMz22sNNNzMzYYDAAAAAABAzMYAIAAwA",
        },
      },
    },
    ["Midnight Falls"] = {
      sampleSize = 49,
      fetchedAt = 1785009452331,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZGzMz2MmZmZmZmwMDAAAAAAY2MmtZYmBzM2mt5BmZMGDLDsMLmxwsppxMzYYDAAAAAABAzMYAIAAwA",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 43,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZGzMz2MmZmZmZmwMDAAAAAAY2MmtZYmBzM2mt5BmZMGDLDsMLmxwsppxMzYYDAAAAAABAzMYAIAAwA",
        },
      },
    },
    ["Windrunner Spire"] = {
      sampleSize = 42,
      fetchedAt = 1785009453464,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 42,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZ2mxMzMGzkxMDAAAAAAYWMmtZYmBmx2sNzMjxALDsMbmxwsopxMzYGbAAAADAABAzMYAIAAwA",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 40,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZ2mxMzMGzkxMDAAAAAAYWMmtZYmBmx2sNzMjxALDsMbmxwsopxMzYGbAAAADAABAzMYAIAAwA",
        },
      },
    },
    ["Maisara Caverns"] = {
      sampleSize = 41,
      fetchedAt = 1785009456415,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 41,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZ2mxMzMGzkxMDAAAAAAYWMmtZYmBmx2sNzMjxALDsMbmxwsopxMzYGbAAAADAABAzMYAIAAwA",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 38,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZ2mxMzMGzkxMDAAAAAAYWMmtZYmBmx2sNzMjxALDsMbmxwsopxMzYGbAAAADAABAzMYAIAAwA",
        },
        {
          heroTreeId = 35,
          heroTreeName = "Aldrachi Reaver",
          sampleSize = 3,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZ2mxMzMGzYGzMAAAAAAgZxY2GMzAzYb2mZmxYglBWmNzYYWYMmZGzYDAAAYAAAAMzgBAAAgB",
        },
      },
    },
    ["Nexus-Point Xenas"] = {
      sampleSize = 38,
      fetchedAt = 1785009457535,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 38,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZ2mxMzMGzkxMDAAAAAAYWMmtZYmBmx2sNzMjxALDsMbmxwsopxMzYGbAAAADAABAzMYAIAAwA",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 37,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZ2mxMzMGzkxMDAAAAAAYWMmtZYmBmx2sNzMjxALDsMbmxwsopxMzYGbAAAADAABAzMYAIAAwA",
        },
      },
    },
    ["Algeth'ar Academy"] = {
      sampleSize = 41,
      fetchedAt = 1785009462562,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 41,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZ2mxMzMGzkxMDAAAAAAYWMmtZYmBmx2sNzMjxALDsMbmxwsopxMzYGbAAAADAABAzMYAIAAwA",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 40,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZ2mxMzMGzkxMDAAAAAAYWMmtZYmBmx2sNzMjxALDsMbmxwsopxMzYGbAAAADAABAzMYAIAAwA",
        },
      },
    },
    ["Magisters' Terrace"] = {
      sampleSize = 33,
      fetchedAt = 1785009463087,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 33,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZ2mxMzMGzkxMDAAAAAAYWMmtZYmBmx2sNzMjxALDsMbmxwsopxMzYGbAAAADAABAzMYAIAAwA",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 31,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZ2mxMzMGzkxMDAAAAAAYWMmtZYmBmx2sNzMjxALDsMbmxwsopxMzYGbAAAADAABAzMYAIAAwA",
        },
      },
    },
    ["Skyreach"] = {
      sampleSize = 38,
      fetchedAt = 1785009477847,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 38,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZ2mxMzMGzkxMDAAAAAAYWMmtZYmBmx2sNzMjxALDsMbmxwsopxMzYGbAAAADAABAzMYAIAAwA",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 38,
          importString = "CEkAG5bbocFKcv+yIq8fPd6ORZmZmZmZ2mxMzMGzkxMDAAAAAAYWMmtZYmBmx2sNzMjxALDsMbmxwsopxMzYGbAAAADAABAzMYAIAAwA",
        },
      },
    },
  },
  [581] = {
    ["Rotmire"] = {
      sampleSize = 50,
      fetchedAt = 1785009478302,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAWmxMzMGzMyMzALmxMYmxMjZegZmZMMz2MjNzMbjhBAAAgZbGMMWWYCDzMjNAAAAMwMzMzs12MzMmZAAAAAYA",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 48,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAWmxMzMGzMyMzALmxMYmxMjZegZmZMMz2MjNzMbjhBAAAgZbGMMWWYCDzMjNAAAAMwMzMzs12MzMmZAAAAAYA",
        },
      },
    },
    ["Imperator Averzian"] = {
      sampleSize = 50,
      fetchedAt = 1785009481990,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAWmxMzMGmRmZGYxMmBzMmZMzDMzMjhZ2mZs9AzMGDDAAAAAAgAmZGbAAAAYgZmZmZptZmZAgBAAAwA",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 42,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAWmxMzMGmRmZGYxMmBzMmZMzDMzMjhZ2mZs9AzMGDDAAAAAAgAmZGbAAAAYgZmZmZptZmZAgBAAAwA",
        },
      },
    },
    ["Vorasius"] = {
      sampleSize = 49,
      fetchedAt = 1785009484125,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAYMzMzMzMjMzMwiZMDmZMzYmHYmZGDzsMzY7BmZMGAAAAAAAIgZmxGAAAAGMmZmZ2abmZGAYAAAAMA",
        },
        {
          heroTreeId = 35,
          heroTreeName = "Aldrachi Reaver",
          sampleSize = 3,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAYMzMjZmZkZmBWMjZwMjZGzMzMzYwsMzYZmZ2GDAAAAY2mBDjlFmwwMzYDAAAADGzMzMLtNzMjZGAAAAAG",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 41,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAYMzMzMzMjMzMwiZMDmZMzYmHYmZGDzsMzY7BmZMGAAAAAAAIgZmxGAAAAGMmZmZ2abmZGAYAAAAMA",
        },
      },
    },
    ["Fallen-King Salhadaar"] = {
      sampleSize = 50,
      fetchedAt = 1785009487216,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAYMzMjZmZkZmBWMjZwMjZGz8AzMzYYmlZGbzMjxAAAAAAAABMzM2AAAAwgxMzMzWbzMzAADAAAgB",
        },
        {
          heroTreeId = 35,
          heroTreeName = "Aldrachi Reaver",
          sampleSize = 2,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAYMzMjZmZkZmBWMjZwMjZGzMzMzYwsMzYZmZ2GDAAAAY2mBDjlFmwwMzYDAAAADGzMzMLtNzMjZGAAAAAG",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 39,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAYMzMjZmZkZmBWMjZwMjZGz8AzMzYYmlZGbzMjxAAAAAAAABMzM2AAAAwgxMzMzWbzMzAADAAAgB",
        },
      },
    },
    ["Vaelgor & Ezzorak"] = {
      sampleSize = 50,
      fetchedAt = 1785009487622,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAYMzMjZmZkZmBWMjZwMjZGzMzMzYwsMzYZmZ2GDAAAAY2mBDjlFmwwMzYDAAAADGzMzMLtNzMjZGAAAAAG",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 45,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAYMzMjZmZkZmBWMjZwMjZGzMzMzYwsMzYZmZ2GDAAAAY2mBDjlFmwwMzYDAAAADGzMzMLtNzMjZGAAAAAG",
        },
      },
    },
    ["Lightblinded Vanguard"] = {
      sampleSize = 50,
      fetchedAt = 1785009489449,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAYMzMjZmZkZmBziZMDmZMzYGzMzYYmlZGbzMjxAAAAAAAABMzM2AAAAwgxMzMzWbzMzAADAAAgB",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 46,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAYMzMjZMzkZmhZWMjZwMjZGzYmZGDmlZGbzMz2YAAAAAAAgAmZGbAAAAYwYmZmZrtZmZAAAAAAG",
        },
      },
    },
    ["Crown of the Cosmos"] = {
      sampleSize = 48,
      fetchedAt = 1785009494977,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAWMmZmxwMyMzALmxMYmxMjZegZmZMMz2MjNzMbjxMAAAAAAACYmZsBAAAgBmZmZml2mZmBAGAAAAD",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 44,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAWMmZmxwMyMzALmxMYmxMjZegZmZMMz2MjNzMbjxMAAAAAAACYmZsBAAAgBmZmZml2mZmBAGAAAAD",
        },
      },
    },
    ["Chimaerus, the Undreamt God"] = {
      sampleSize = 49,
      fetchedAt = 1785009495089,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAYMzMjxMjMzMYWMjZwMjZGzYmZGDzsNzY7BmZ2GDAAAAAAAEwMzYDAAAADmZmZmZrtZmZAgBAAAwA",
        },
        {
          heroTreeId = 35,
          heroTreeName = "Aldrachi Reaver",
          sampleSize = 2,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAYMzMjZmZkZmBWMjZwMjZGzMzMzYwsMzYZmZ2GDAAAAY2mBDjlFmwwMzYDAAAADGzMzMLtNzMjZGAAAAAG",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 43,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAYMzMjZmZkZmBWMzMDmZMzYGzMzYYmtZGbzMjxAAAAAAAABMzM2AAAAwAzMzMzWbzMzAADAAAgB",
        },
      },
    },
    ["Belo'ren, Child of Al'ar"] = {
      sampleSize = 50,
      fetchedAt = 1785009498114,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZMzMjMzMMziZMjhZMDzYmZGDzsMzYzMz2YAAAAAAAgAmZGbAAAAYwYmZmZrtZmZAgBAAAwA",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 44,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZMzMjMzMMziZMDmZMDzYmZGDzsMzYxMz2YAAAAAAAgAmZGbAAAAYwYmZmZptZmZAgBAAAwA",
        },
      },
    },
    ["Midnight Falls"] = {
      sampleSize = 49,
      fetchedAt = 1785009498177,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZMzMjMzMYWMjZwMjZGzYmZGDzsMzYzMz2YAAAAAAAgAmZGbAAAAYwYmZmZrtZmZAgBAAAwA",
        },
        {
          heroTreeId = 35,
          heroTreeName = "Aldrachi Reaver",
          sampleSize = 2,
          importString = nil,
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 46,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZMzMkZmhZWMjZwMjZYGzMzYYmlZGbmZ2GDAAAAAAAEwMzYDAAAADmZmZmZptZmZAgBAAAwA",
        },
      },
    },
    ["Windrunner Spire"] = {
      sampleSize = 40,
      fetchedAt = 1785009500844,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 40,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZmhZkZmBziZMDmZMzYmHYmZGDmtZGbPwMz2YYAAAAAAAEwMzYDAAAADMzMzMbtNzMDAAAAAwA",
        },
        {
          heroTreeId = 35,
          heroTreeName = "Aldrachi Reaver",
          sampleSize = 4,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAWmxMzMGmRmZGYxMmBzMmZMzDMzMjhZ2mZsZmZbMmBAAAgZbGMMW2YCDzYsAAAAgBmZmZmt2mZmxMDwAAAAYA",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 34,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZmhZkZmBziZMDmZMzYmHYmZGDmtZGbPwMz2YYAAAAAAAEwMzYDAAAADMzMzMbtNzMDAAAAAwA",
        },
      },
    },
    ["Maisara Caverns"] = {
      sampleSize = 36,
      fetchedAt = 1785009503754,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 36,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZMMjMzMYWMjZwMjZGzMjZGDmtZGbzMz2YMDAAAAz2MYYssxEGmZYDAAAADMzMzMbtNzMjZGAAAAAG",
        },
        {
          heroTreeId = 35,
          heroTreeName = "Aldrachi Reaver",
          sampleSize = 3,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAWmxMzMGmRmZGYxMmBzMmZMzDMzMjhZ2mZsZmZbMmBAAAgZbGMMW2YCDzYsAAAAgBmZmZmt2mZmxMDwAAAAYA",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 31,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZmhZkZmBziZMDmZMzYmHYmZGDmtZGbPwMz2YYAAAAAAAEwMzYDAAAADMzMzMbtNzMDAAAAAwA",
        },
      },
    },
    ["Nexus-Point Xenas"] = {
      sampleSize = 33,
      fetchedAt = 1785009507778,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 33,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZMMzkZmhZWMjZwMjZGzYmZGDmtZGbmZ2GjZAAAAAAAEwMjZDAAAADMzMzMbtNzMDAAAAAwA",
        },
        {
          heroTreeId = 35,
          heroTreeName = "Aldrachi Reaver",
          sampleSize = 5,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZMMjMzMwiZMDmZMzYmZmZGDmtZGbPwMz2YMDAAAAz2MYYsswEGmZGLAAAAYgZmZmZrtZmZMzAAAAAwA",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 26,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZMMzkZmhZWMjZwMjZGzYmZGDmtZGbmZ2GjZAAAAAAAEwMjZDAAAADMzMzMbtNzMDAAAAAwA",
        },
      },
    },
    ["Algeth'ar Academy"] = {
      sampleSize = 33,
      fetchedAt = 1785009508480,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 33,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZmhZkZmBziZMDmZMzYmHYmZGDmtZGbPwMz2YYAAAAAAAEwMzYDAAAADMzMzMbtNzMDAAAAAwA",
        },
        {
          heroTreeId = 35,
          heroTreeName = "Aldrachi Reaver",
          sampleSize = 4,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAWmxMzMGmRmZGYxMmBzMmZMzDMzMjhZ2mZsZmZbMmBAAAgZbGMMW2YCDzYsAAAAgBmZmZmt2mZmxMDwAAAAYA",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 29,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZmhZkZmBziZMDmZMzYmHYmZGDmtZGbPwMz2YYAAAAAAAEwMzYDAAAADMzMzMbtNzMDAAAAAwA",
        },
      },
    },
    ["Magisters' Terrace"] = {
      sampleSize = 36,
      fetchedAt = 1785009514193,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 36,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZMMjMzMYWMjZwMjZGzMjZGDmtZGbzMz2YMDAAAAz2MYYssxEGmZYDAAAADMzMzMbtNzMjZGAAAAAG",
        },
        {
          heroTreeId = 35,
          heroTreeName = "Aldrachi Reaver",
          sampleSize = 2,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAWmxMzMGmRmZGYxMmBzMmZMzDMzMjhZ2mZsZmZbMmBAAAgZbGMMW2YCDzYsAAAAgBmZmZmt2mZmxMDwAAAAYA",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 34,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZMMjMzMYWMjZwMjZGzMjZGDmtZGbzMz2YMDAAAAz2MYYssxEGmZYDAAAADMzMzMbtNzMjZGAAAAAG",
        },
      },
    },
    ["Pit of Saron"] = {
      sampleSize = 37,
      fetchedAt = 1785009516965,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 37,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZmhZkZmBziZMDmZMzYmHYmZGDmtZGbPwMz2YYAAAAAAAEwMzYDAAAADMzMzMbtNzMDAAAAAwA",
        },
        {
          heroTreeId = 35,
          heroTreeName = "Aldrachi Reaver",
          sampleSize = 3,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAWmxMzMGmRmZGYxMmBzMmZMzDMzMjhZ2mZsZmZbMmBAAAgZbGMMW2YCDzYsAAAAgBmZmZmt2mZmxMDwAAAAYA",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 33,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZmhZkZmBziZMDmZMzYmHYmZGDmtZGbPwMz2YYAAAAAAAEwMzYDAAAADMzMzMbtNzMDAAAAAwA",
        },
      },
    },
    ["Seat of the Triumvirate"] = {
      sampleSize = 34,
      fetchedAt = 1785009517110,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 34,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAWmxMzMGmRmZGMLmxMYmxMjZegZmZMY2mZsZmZbMmBAAAAbzghhFmwwMzYDAAAADMzMzMbtNzMDzAAAAAwA",
        },
        {
          heroTreeId = 35,
          heroTreeName = "Aldrachi Reaver",
          sampleSize = 5,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZMMjMzMwiZMDmZMzYmZmZGDmtZGbPwMz2YMDAAAAz2MYYsswEGmZGLAAAAYgZmZmZrtZmZMzAAAAAwA",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 28,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZMmZwMzALmxMYmxMjZmZmZMY2mZsZmZbMMAAAAAAAAMzM2AAAAwAzMzMzmtZmZAgBAAAwA",
        },
      },
    },
    ["Skyreach"] = {
      sampleSize = 21,
      fetchedAt = 1785009522732,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 21,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZmhZmMzMwiZMDmZMzYmZmZGDmtZGbmZ2GjZAAAAAAAEwMGbAAAAYgZmZmZrtZmZAAAAAAG",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 19,
          importString = "CUkAG5bbocFKcv+yIq8fPd6ORBAMjZmZmhZmMzMwiZMDmZMzYmZmZGDmtZGbmZ2GjZAAAAAAAEwMGbAAAAYgZmZmZrtZmZAAAAAAG",
        },
      },
    },
  },
  [1480] = {
    ["Vaelgor & Ezzorak"] = {
      sampleSize = 47,
      fetchedAt = 1785009538067,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 47,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzMzMGmBAAAAAAgxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 39,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzMzMGmBAAAAAAgxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
      },
    },
    ["Lightblinded Vanguard"] = {
      sampleSize = 48,
      fetchedAt = 1785009538350,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 48,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2MmZmZmZmxwMAAAAAAAegxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 32,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzMzMGmBAAAAAAgxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwMzsMzMNbzsNjBjZA",
        },
      },
    },
    ["Crown of the Cosmos"] = {
      sampleSize = 49,
      fetchedAt = 1785009548575,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzMzMGmBAAAAAAgxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 2,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBAWMmZmZmZmxwMAAAAAAAegxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 38,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzMzMGmBAAAAAAgxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
      },
    },
    ["Chimaerus, the Undreamt God"] = {
      sampleSize = 50,
      fetchedAt = 1785009548692,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 50,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBAWmxMzMzMzMGmBAAAAAAgxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 37,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBAWmxMzMzMzMGmBAAAAAAgxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
      },
    },
    ["Belo'ren, Child of Al'ar"] = {
      sampleSize = 49,
      fetchedAt = 1785009553307,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzYmxwMAAAAAAAMmthZGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
        {
          heroTreeId = 34,
          heroTreeName = "Fel-Scarred",
          sampleSize = 3,
          importString = nil,
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 28,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBAWmxMzMzYmxwMAAAAAAAMmthZGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
      },
    },
    ["Midnight Falls"] = {
      sampleSize = 49,
      fetchedAt = 1785009553370,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 49,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzMzMGmBAAAAAAgxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 45,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzMzMGmBAAAAAAgxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
      },
    },
    ["Windrunner Spire"] = {
      sampleSize = 37,
      fetchedAt = 1785009555719,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 37,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzMzMGmBAAAAAAgxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 8,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzMzMGmBAAAAAAgxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
      },
    },
    ["Maisara Caverns"] = {
      sampleSize = 17,
      fetchedAt = 1785009556512,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 17,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzYmxwMAAAAAAAMmthZGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 8,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzMzMGmBAAAAAAgxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
      },
    },
    ["Nexus-Point Xenas"] = {
      sampleSize = 33,
      fetchedAt = 1785009560854,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 33,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzYmxwMAAAAAAAMmthZGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 33,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzYmxwMAAAAAAAMmthZGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
      },
    },
    ["Algeth'ar Academy"] = {
      sampleSize = 36,
      fetchedAt = 1785009560995,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 36,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzYmxwMAAAAAAAMmthZGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 36,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzYmxwMAAAAAAAMmthZGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
      },
    },
    ["Magisters' Terrace"] = {
      sampleSize = 34,
      fetchedAt = 1785009566735,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 34,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzMzMGmBAAAAAAgxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 6,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzYmxwMAAAAAAAMmthZGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
      },
    },
    ["Pit of Saron"] = {
      sampleSize = 36,
      fetchedAt = 1785009567322,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 36,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzYmxwMAAAAAAAMmthZGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 8,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzYmxwMAAAAAAAMmthZGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
      },
    },
    ["Seat of the Triumvirate"] = {
      sampleSize = 33,
      fetchedAt = 1785009568889,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 33,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBAWmxMzMzYmxwMAAAAAAAMmthZGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 11,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzYmxwMAAAAAAAMmtxDYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
      },
    },
    ["Skyreach"] = {
      sampleSize = 39,
      fetchedAt = 1785009569603,
      variants = {
        {
          heroTreeId = nil,
          heroTreeName = "Overall",
          sampleSize = 39,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBAWmxMzMzYmxwMAAAAAAAMmthZGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
        {
          heroTreeId = 124,
          heroTreeName = "Annihilator",
          sampleSize = 11,
          importString = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mxMzMzMzMGmBAAAAAAgxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
        },
      },
    },
  },
}
